README.md
=> docs(README): update documentation for development

package-lock.json
=> chore(*): build for pushing

nwb.config.js, package-lock.json, package.json, src/TemplateLibrary/TemplateCard.js, src/TemplateLibrary/index.js, src/index.js
No Issue
Updated nwb configuration for webpack customization
Added a fetch call through cicero-core to AP template library
FLAGS:
cicero-core's `TemplateLibrary` cause me to change the component to `TemplateLibraryComponent`
Yet to cross check these changes with an `npm link` with template-studio-v2
=> feat(*): configure nwb webpack and successful fetch from ap

src/TemplateLibrary/index.js
Issue #6 
Update component to pass the Template Library up and render what is passed back down.
=> feat(src): utilize redux saga action from props

README.md, package-lock.json, package.json, src/TemplateLibrary/__snapshots__/index.test.js.snap, src/TemplateLibrary/index.test.js, src/utilities/test/jestEnzyme.js
Issue #6 
- Update instructions
- Install and initiate JEST testing with a snapshot
**FLAGS**:
- Testing with mock template data could be a good future step.
=> feat(*): initiate jest testing with snapshot - I6

.gitignore, .travis.yml
=> (test) Initial Travis configuration + fix to gitignore

package.json
=> chore(package): increment version for npm publish - I6

.travis/deploy.sh
=> (fix) travis key variables

package.json
=> (fix) Scripts targets in package.json

package.json
=> (fix) publish target

.travis.yml
=> (fix) Add transpilation to test

__mocks__/styleMock.js, package-lock.json, package.json, src/ErrorLogger/README.md, src/ErrorLogger/__snapshots__/index.test.js.snap, src/ErrorLogger/index.js, src/ErrorLogger/index.test.js, src/index.js
https://github.com/accordproject/cicero-ui/issues/17
feat(ErrorLogger): migrate error logger and refactor as functional component
test(ErrorLogger): add snapshot and configure jest mock
**FLAGS**
Corresponds with [PR in template-studio-v2](https://github.com/accordproject/template-studio-v2/pull/29)
=> feat(ErrorLogger): migrate error logger and refactor as functional component - 17

package-lock.json, src/ClauseEditor/__snapshots__/index.test.js.snap, src/TemplateLoadingClauseEditor/__snapshots__/index.test.js.snap
=> (test) Update snapshots for latest ClauseEditor changes

.travis.yml, package-lock.json, package.json
=> (chore) Bump to Markdown 0.4.5

package-lock.json, package.json
- Run `npm audit fix` to address **6** vulnerabilities (**3** moderate, **3** high)
- **1** vulnerabilities remains (low)
- Updates to latest stable verrsion of `accordproject/cicero-core`
=> fix(package): fix npm vulnerabilities

src/components/ClauseComponent.js
=> fix(ClauseComponent): fix casing for contentEditable prop

package-lock.json, package.json, src/ClauseEditor/index.js
=> chore(markdown-editor): bump markdown-editor dependency to 0.4.15

src/TemplateLibrary/index.js
- Corrects paragraph styling
- N/A
- Issue #6
- Pull Request #66, #68, #69, and #70
=> fix(TemplateLibrary): adjust paragraph css - I62

demo/src/index.js, package-lock.json, package.json
=> chore(dep) Bump to Cicero 0.13 & MD 0.5

package-lock.json, package.json
This upgrades the Cicero version used by Cicero UI to 0.13.2
=> chore(dep) Bump to Cicero 0.13.2

src/index.js, src/plugins/ClausePlugin.js
- export `ClausePlugin` so it can be correctly imported by TSv2 [here](https://github.com/accordproject/template-studio-v2/blob/787e4d74a41289f96502a5a0d651cf691f6ec747/src/sagas/contractSaga.js#L7) or by other apps
=> chore(ClausePlugin): export ClausePlugin

CHARTER.md, README.md
- Initiate Linux Foundation charter as a markdown file.
- N/A
- N/A
=> docs(CHARTER): implement linux foundation charter - I65

package-lock.json, src/TemplateLibrary/TemplateCard.js, src/TemplateLibrary/index.js
Correct bug for exporting this component into other webapps.
- Utilize conditional props for design:
- Template Cards have optional border
- Template Library cards section has conditional height for scrolling
- Fix `Searchbar` styling
- Once this publishes to `npm`, @irmerk will increment in TSv2 to create PR with these new props.
- [TSv2 Issue 61](https://github.com/accordproject/template-studio-v2/issues/61)
=> fix(TemplateLibrary): correct styling with conditional props - I6

README.md
Signed-off-by: Peter Hunn <peter@peterhunn.com>
=> docs(README): add trademark policy - I65

demo/src/index.js, src/plugins/ClausePlugin.js
fix(ClausePlugin): update naming of clauseid attribute to be consistent with naming used in TSv2
=> fix(ClausePlugin): update naming of clauseid attribute to be consistent

package.json, yarn.lock
- Revert to latest stable version of Cicero (0.13.4)
=> fix(dependencies) Uses a development version of Cicero

README.md, src/ContractEditor/README.md, src/TemplateLibrary/README.md
Update documentation to reflect the current status of the repository, and sync up this tech stack for stability.
- Provide a list of components which are ready for use and another which is in development
- Provide a quick guide instructions
- Refine code structure
- Update individual instructions for `TemplateLibrary` and `ContractEditor`
- Abstract out styling information to individual `README` files
- Further information is needed for: 
- `ParseResult`
- `TemplateLoadingClauseEditor`
- Please read through the instructions to see if they also make sense to you.
- N/A
=> docs(README): update instructions and structure

README.md, src/index.js
chore(index): export variable plugin
=> chore(index): export variable plugin

src/ErrorLogger/index.js, src/ErrorLogger/styles.js
- Extending last PR to apply `z-index` where needed
N/A
- Pull Request #112
=> fix(ErrorLogger): apply zindex to header component

src/plugins/ClausePlugin.js
feat(ClausePlugin): add query for finding clause node by id
=> feat(ClausePlugin): add query for finding clause node by id

demo/src/index.js, package-lock.json, package.json, src/ContractEditor/index.js, src/plugins/ClausePlugin.js, src/plugins/VariablePlugin.js
Paused for a worrk in progress of utilizing the new `markdown-transform` library
=> chore(*): work in progress for markdown-transform

README.md
- added Slack badge
- accordproject/techdocs/issues/82
- accordproject/techdocs/issues/78
=> docs(README): add slack badge

DEVELOPERS.md
Signed-off-by: Sanket Shah <er.sanketshah@gmail.com>
Correct typo in URL to add main repository as upstream in DEVELOPERS.md document
=> fix(DEVELOPERS): correct typo to add main repository as upstream

src/plugins/ClausePlugin.js
fix(ClausePlugin): update last argument passed to parseClauseCallback to be clauseid
=> fix(ClausePlugin): update last argument passed to parseClauseCallback to be clauseid

src/plugins/ClausePlugin.js
fix(ClausePlugin): fix findClauseNode when getting clause id from node data
=> fix(ClausePlugin): fix findClauseNode when getting clause id from node data

package-lock.json, package.json
=> chore(package): increment markdown editor

README.md
Signed-off-by: Dmitry <daniloff200@gmail.com>
https://github.com/accordproject/techdocs/issues/80#issuecomment-544871864
=> fix(readme): fix broken link in readme

package-lock.json, package.json
=> chore(dep) Upgrade to markdown-transform 0.6.0

package-lock.json, package.json
chore(deps): update markdown editor dependency to 0.6.5
=> chore(deps): update markdown editor dependency to 0.6.5

README.md
* fix typo in plugin name
* add links to plugin `README`
* fix missing closing tag
Signed-off-by: Kedar Thakur <453473+starblind@users.noreply.github.com>
* add links to plugin `README`
* fix missing closing tag
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>
=> fix(README): various

README.md
- Fix readme typo
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>
=> fix(README): typo - I203

README.md, src/ErrorLogger/README.md, src/plugins/README.md
Signed-off-by: Kedar Thakur <453473+starblind@users.noreply.github.com>
misc README fixes
* use syntax highlighting
* add some notes about `ClausePlugin`
* add missing links
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>
=> docs(README): plugins updates

package.json, src/Navigation/index.test.js
Signed-off-by: Kedar Thakur <453473+starblind@users.noreply.github.com>
unit tests + add coverage script
* add a script for test coverage
* add some unit tests
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>
=> test(Navigation): init unit tests - I123

src/ContractEditor/index.test.js
=> chore(test): comment out test

package-lock.json, package.json
=> chore(package): increment markdown-editor

package-lock.json, package.json
- https://github.com/accordproject/cicero-ui/issues/211
- https://github.com/accordproject/cicero-ui/issues/210
- https://github.com/accordproject/cicero-ui/issues/209
chore(deps): update markdown-editor to fix toolbar bug on locked text
=> chore(deps): update markdown-editor to fix toolbar bug on locked text

package-lock.json, package.json
chore(deps): upgrade to markdown-editor 0.7.6
=> chore(deps): upgrade to markdown-editor 0.7.6

package-lock.json, package.json, src/ContractEditor/README.md, src/ContractEditor/index.js, src/components/ClauseComponent.js, src/components/styles.js, src/index.js, src/plugins/ClausePlugin.js, src/plugins/ConditionalPlugin.js, src/plugins/README.md, src/utilities/inConditional.js
- Conditional variables plugin (#233)
- Query to detect slate DOM nodes that are currently unsupported in the UI (#237)
- Switch to latest dev version of Cicero and Markdown transform `0.9.1`
- New Conditionals plugin
- New helper, new plugin, new color, new readme
- Initial `isClauseSupported` query in the Clause Plugin
=> Support (and non-support) for new templates syntax

src/plugins/ClausePlugin.js
- Adjust clause plugin query for non-supported features in the UI so it throws an error
=> fix(ClausePlugin) is Clause supported call now throws errors

src/plugins/ClausePlugin.js
- fix(ClausePlugin): fix paste in ClausePlugin
- FYI my linter auto-formatted some other things in that file
=> fix(ClausePlugin): fix paste in ClausePlugin

src/TemplateLibrary/index.js, src/styles.css
feat(TemplateLibrary): update cursor to be same color as search text
- Issue #241
=> feat(TemplateLibrary): update cursor to be same color as search text

src/TemplateLibrary/index.js, src/styles.css
=> fix(styles): remove semantic-ui styling overrides

package-lock.json, package.json
=> chore(dep) Upgrade to Cicero 0.20.6

package-lock.json, package.json, src/ContractEditor/README.md, src/ContractEditor/index.js
=> chore(ContractEditor): pass height props to editor

package-lock.json, src/ContractEditor/__snapshots__/index.test.js.snap, src/ContractEditor/index.js, src/ContractEditor/index.test.js
Fix issue where the test failed when using `getByRole` method. Changed with [byTestId](https://testing-library.com/docs/dom-testing-library/api-queries#bytestid).
Something wrong with that method, because it return text input as well. (I did not debug their code).
- Fix the failing test
Sorry for delay.
=> test(ContractEditor): update selector to use getByTestId - I34

package-lock.json, package.json
- chore(deps): update markdown-editor and markdown-slate dependencies
=> chore(deps): update markdown-editor and markdown-slate dependencies

src/plugins/ClausePlugin.js
- feat(ClausePlugin): adds a query to check if the user is outside of a clause 
- This will allow users of cicero-ui to check if a user is outside of a clause before performing some action like adding a clause
=> feat(ClausePlugin): adds a query to check if the user is outside of a clause

package-lock.json, package.json
chore(dep): increment md editor to 0.9.2
=> chore(dep): increment md editor to 0.9.2

package-lock.json, package.json
=> chore(dep) Upgrade to Markdown Transform 0.9.7 and Editor 0.9.3

package-lock.json, package.json
chore(deps): update md editor and transform dependencies
=> chore(deps): update md editor and transform dependencies

package-lock.json, package.json, src/ContractEditor/index.test.js
=> chore(dep): update md editor to 0.9.5

package-lock.json, package.json, src/plugins/ClausePlugin.js
=> chore(dep) Upgrade to Markdown Transform 0.9.9, remove obsolete 'quote'

.gitignore
Signed-off-by: adrijshikhar <adrijshikhar85@gmail.com>
- Update .gitignore
- add .vscode and .dist in .gitignore
- N/A
- N/A
=> fix(gitignore): add .vscode and .dist in .gitignore - I289

src/TemplateLibrary/index.js
Signed-off-by: adrijshikhar <adrijshikhar85@gmail.com>
fix #269 
- Fix no highlight color of text in `SearchInput`
- Change `:selection` pseudo-class `SearchInput` component on line 74
- Snapshot
=> fix(TemplateLibrary): fixed highlighting of text on selection in SeachInput - I269

src/components/ClauseComponent.js, src/plugins/ClausePlugin.js
Allow clause templates with conditional variables.
=> chore(plugins): remove conditional clause error - I233

README.md
docs(README): add netlify to README
=> docs(README): add netlify to README

src/TemplateLibrary/Components/TemplateActions.js, src/TemplateLibrary/Components/TemplateCard.js, src/Tile/TextForm.js
- Certain template components written as Class-based components have been refactored as functional components using Hooks and ```React.Memo``` (for pure components)
- The components have been tested directly on template-studio-v2 
- Side change :
Also fixes https://github.com/accordproject/template-studio-v2/issues/135
=> refactor(*): template class components to functional - I293

src/components/styles.js
Signed-off-by: elit-altum <manan.sharma311@gmail.com>
- Changes the ```ClauseHeader``` background gradient from ```#ECF0FA``` to ```#F9FBFF```
- Issue #322
=> style(ClauseHeader): changed header background - I322

README.md
Signed-off-by: Sanyam Dogra <sdlord07@gmail.com>
Removed the links leading to 404.
Removed links for following-
- `ClauseEditor`
- `TemplateLoadingClauseEditor`
- N.A
- N.A
=> docs(readme): Remove 404 links- I328

package-lock.json, package.json
Update to [`markdown-editor` v0.9.12](https://github.com/accordproject/markdown-editor/releases/tag/v0.9.12)
=> chore(package): inc mde

demo/src/index.js, package.json, src/TemplateLibrary/Buttons/index.js
Signed-off-by: Sanyam Dogra <sdlord07@gmail.com>
Added `aria-label` in Buttons for better accessibility on screen readers etc.
Added `aria-label` in
- TemplateLibrary
- Demo
- N.A
- N.A
=> feat(Button): aria-label for Button accessibility -I55

package-lock.json, package.json
=> chore(package): support for mde 9.15

src/components/ClauseComponent.js, src/components/Conditional.js, src/components/styles.js, src/styles.css
Signed-off-by: elit-altum <manan.sharma311@gmail.com>
Adds feature to highlight/add border to variables.
- src/components/styles.js 
-  src/plugins/VariablePlugin.js
- N/A
- N/A
=> feat(*): add background colors and borders to variables - I314

src/plugins/ConditionalPlugin.js
Signed-off-by: jerrybuks <profkiti@gmail.com>
fixed feature/bug that allowed editing of conditional variables.
- made changes to the ConditionalPlugin file
- A user could previously edit conditional variables.
- N/A
=> fix(ConditionalPlugin) fixed feature allowing conitionals editing -I339

CONTRIBUTING.md, DEVELOPERS.md, README.md
- Put `ConditionalPlugin` in `README`
- Point `CONTRIBUTING` and `DEVELOPERS` to `development` branch
- Update syncing `master` instructions
- Misc. cleanup
=> docs(*): point PRs to development

package-lock.json, package.json
- Updates markdown-editor to latest UNstable release
=> chore(dep): update markdown-editor

demo/src/index.js, package-lock.json, package.json, src/ContractEditor/index.js, src/ContractEditor/plugins/withClauses.js, src/ContractEditor/test/index.test.js, src/components/index.css, src/stories/ContractEditor/ContractEditor.stories.js, src/stories/Demo/Demo.stories.js
Support parsing, most notably in the demo
- Maintain the debounce for parsing
- Setup redux store for parsing in the demo
- `cicero-ui` does not parse on it's own, the parent component / consumer will need to do this
=> feat(*): support clause parsing

package-lock.json, package.json, src/ContractEditor/index.js
- Allows parent of Contract Editor to also augment the slate editor
- Updates dependencies
=> feat(ContractEditor): add augmentEditor prop and update deps

src/ContractEditor/index.js, src/ContractEditor/plugins/withClauses.js, src/ContractEditor/plugins/withVariables.js
Check if forward delete is at the end of a node and before a clause
=> fix(ContractEditor): prevent fwd delete before clause - I403

src/ContractEditor/plugins/withClauses.js
=> fix(withClauses): call pasteToContract from props

package-lock.json, package.json, src/ContractEditor/index.js, src/ContractEditor/plugins/withClauses.js, src/ContractEditor/test/__snapshots__/index.test.js.snap, src/components/Clause/index.js, src/components/Conditional/index.js, src/components/styles.js, src/icons/add.js, src/icons/remove.js
- Updates markdown-editor version
- Cleans up code to resolve console warnings
=> refactor(*): refactor and clean up

src/ContractEditor/plugins/withClauses.js
=> fix(withClauses): return so we dont insertData twice
