CONTRIBUTING.md, DEVELOPERS.md, LICENSE, README.md, markdown-license.txt, src/ContractEditor/README.md, src/TemplateLibrary/README.md
- Update project structure and badges
- Implement license file 
- Add markdown license file
- Implement readme for `ContractEditor` and `TemplateLibrary`
- Implement developer and contribution instructions
- Markdown license file may be unnecessary. 
- This was following @mttrbrts's commit here: https://github.com/accordproject/cicero/commit/93ff83e48691c913f5351389cf72b44cd8460593
=> docs(*): documentation for this repository - I37

package-lock.json, src/ClauseEditor/__snapshots__/index.test.js.snap, src/ClauseEditor/index.test.js, src/ContractEditor/index.test.js, src/ErrorLogger/index.test.js, src/TemplateLibrary/TemplateActions.js, src/TemplateLibrary/TemplateCard.js, src/TemplateLibrary/__snapshots__/index.test.js.snap, src/TemplateLibrary/index.js, src/TemplateLibrary/index.test.js, src/TemplateLoadingClauseEditor/__snapshots__/index.test.js.snap, src/TemplateLoadingClauseEditor/index.test.js
- Update snapshots
- Pass in props in tests for `PropType` warnings
- Add class names for testing
- Implement further tests for `TemplateLibrary`
- Corrected import name in `src/ClauseEditor/index.test.js`
- Attempted `chai`, but abandoned when `effect` keyword was conflicting
=> test(TemplateLibrary): implement test and fix proptypes - I-35

src/ContractEditor/index.js
updated the storeLocal function to match the updated example in the markdown-editor [here](https://github.com/accordproject/markdown-editor/blob/77d3a887c0e195bd90e1fadf68f29989731c5554/examples/src/index.js#L12)
=> fix(storeLocal): fix storeLocal function

package-lock.json, package.json, src/ContractEditor/plugins/clausePlugin.js, webpack.config.js
chore(webpack): webpack updates to allow for npm linking markdown editor
fix(clausePlugin): add new lines before instead of after clause
fix(clausePlugin): separate src and id attributes so that there is a space between the two
=> fix(clausePlugin): fix toMarkdown to accommodate id attribute and add new lines before clause

package-lock.json, src/ContractEditor/index.js, src/plugins/ClausePlugin.js
fix(ClauseComponent): fix getting clauseId from attributes
- the clauseId is converted to all lowercase when it is an attribute in the markdown, so we need to look for `clauseid` when getting it from attributes
- this fix will allow for the clause id to be rendered in the title of the clause component
=> fix(ClauseComponent): fix getting clauseId from attributes

src/TemplateLibrary/index.js
Correction to styling for importing to a third party. Was unable to `npm link` prior to #66.
- Remove unnecessary margins
- Template Studio v2 will need to use the latest `npm` version, which will not be an incremented pre-release.
- Pull Request #66
=> fix(TemplateLibrary): remove margins for imports - I62

src/TemplateLibrary/index.js
- Correction to `props` for function to view details of template.
- N/A
- Pull Request #66 and #68
=> fix(TemplateLibrary): correct props declaration - I62

package-lock.json, package.json, src/ClauseEditor/index.js, src/ContractEditor/index.js
- update markdown-editor to v0.5.4
- update propTypes (`parseClause` and `loadTemplateObject` are not required because `ClausePlugin` uses default methods for these if nothing is passed in)
=> chore(*): update markdown-editor version and update propTypes

src/ErrorLogger/index.js, src/TemplateLibrary/TemplateCard.js
Refactor and prepare `ErrorLogger` to be imported with functionality
- Unrelated addition to `TemplateLibrary` to render `displayName` only if it exists
- Uses function passed from props to handle the individual clause the error refers to
- A separate PR will be put in for the styling additions
- Future work is needed to clean up the functionality of clicking on different areas of errors
- [TSv2 Issue 61](https://github.com/accordproject/template-studio-v2/issues/61)
=> feat(ErrorLogger): handle error navigation - I17

package-lock.json, package.json, src/ClauseEditor/__snapshots__/index.test.js.snap, src/ContractEditor/index.js
feat(ContractEditor): forward ref to SlateAsInputEditor
https://github.com/accordproject/markdown-editor/pull/76
=> feat(ContractEditor): forward ref to SlateAsInputEditor

src/Navigation/styles.js
Removes unnecessary background from header navigation scrollbar
- Change `webkit-scrollbar-track` to more accurate component
N/A
N/A
=> fix(styles): correct scrollbar background - I110

src/Navigation/styles.js
Remove unnecessary grid attribute causing spacing issues
- Remove unnecessary grid attribute causing spacing issues
N/A
- Issue #91
=> fix(Navigation): remove unnecessary grid in contracts

src/plugins/ClausePlugin.js
fix(ClausePlugin): use loadTemplateCallback in rewriteClause
By using `loadTemplateCallback`, we will use the custom load template function if one is passed in before falling back to the `loadTemplate` method defined in this plugin.
=> fix(ClausePlugin): use loadTemplateCallback in rewriteClause

package-lock.json, package.json, src/plugins/ClausePlugin.js
Create new `uuid` for a clause that was copy/pasted in conjunction with [this PR in `markdown-editor`](https://github.com/accordproject/markdown-editor/pull/89)
- On a paste event, we take the `Document` on the event and make it mutable in order to change the `clauseid` to a `uuid` and revert everything to immutable
- Abstracted clause specific logic out of `@accordproject/markdown-editor`
- Further issues should consider:
- Handling different `transfer.type` situations
- Editor instance (Slate) to another editor instance (Slate)
- Raw `HTML` (Chrome to VSCode to Chrome)
- Editor instance (Slate) to Google Docs and back (recognize `<clause>` formatting)
- Ensure `onPaste` handlers are not doubling up work for any `transfer.type` cases
- `@accordproject/cicero-ui/src/plugins/ClausePlugin` …
=> feat(ClausePlugin): handle paste functionality with clauses - I134

package-lock.json, package.json, webpack.config.prod.js
Address outstanding issue of `webpack` from [`markdown-editor` PR #86](https://github.com/accordproject/markdown-editor/pull/86) not working for local development, brought up by @KaustubhD and @Anisha1234
- Split `webpack` configs and `npm` scripts to handle development and production environments
- Instructions in the `README` will need further updating and polishing
- Reviewers should ensure testing this in dev (isolated) and also in TSv2 (`npm link`)
- [`markdown-editor` PR #86](https://github.com/accordproject/markdown-editor/pull/86)
- [`markdown-editor` Issue #85](https://github.com/accordproject/markdown-editor/issues/85)
- [`markdown-editor` Issue #90](https://github.com/accordproject/markdown-editor/issues/90)
=> fix(*): split webpack config to handle local dev

package-lock.json, src/plugins/ClausePlugin.js
Parse an add any necessary annotations to clauses as they are pasted
- Adapt `removeParseAnnotations` function to only remove annotations from the specific clause in question
- `parsePastedClauses` mimics `onChange`, but is run for each clause within a pasted fragment
- The hash for the annotation is adapted to account for a `clauseId` for better stability in differentiating clauses' annotations
- Current issue is that the annotation is not added to display red in the editor when a clause with parse errors is copy/pasted. When clicking inside the pasted clause, the annotation is immediately displayed.
- Issue #134
=> feat(plugins): parse clauses on paste - I141

src/ErrorLogger/actions.js, src/ErrorLogger/index.js
Small typo fix in code
Change **isMultpleErrors** to **isMultipleErrors**
=> fix(ErrorLogger): typo in errors check const name

package-lock.json, src/components/ClauseComponent.js, src/components/__snapshots__/index.test.js.snap, src/components/actions.js, src/components/index.test.js, src/components/styles.js
hovering over clause template header title will pop up a tooltip if header has been truncated.
- use named imports instead of default from `actions` to utilize `titleGenerator` function to display title on tooltip.
- create state for hover effect.
- tooltip pops up with full title if header is truncated (> 54 characters in length) and hovered over.
- Images following, hovering when header title is not truncated:
- hovering when header title is truncated:
- 
- Issue #121 
- Issue #120
=> feat(components) add header tooltip - I120

src/ErrorLogger/Error.js, src/ErrorLogger/README.md, src/ErrorLogger/actions.js, src/ErrorLogger/index.js, src/ErrorLogger/index.test.js
Signed-off-by: Pawel -Muody- Kochanek <pawel.kochanek@gmail.com>
ErrorLogger was accepting an array of objects and there was possible issue with duplicate errors. The task was to change array to object.
- change 'errorComponentGenerator' function. Right now it's mapping over keys of error object, not array as before.
- change propTypes, not errors are required object, not array
- change error value in tests
- in action.js, instead errors.length, we use Object.keys(errors).length.
- There were not many changes I made, main change was iteration over Object.keys instead of errors array. The rest was written such a way I just made some fine tuning. Also in tests I just change the errors object structure. After that, all errors passed.
=> feat(ErrorLogger): accept object instead array - I137

CONTRIBUTING.md
Signed-off-by: Arshad Kazmi <arshadkazmi42@gmail.com>
This PR fixes the broken link of code of conduct in CONTRIBUTING.md file
- Change the old code of conduct url (`https://github.com/accordproject/docs/blob/master/Accord%20Project%20Code%20of%20Conduct.pdf`) to new url (`https://lfprojects.org/policies/code-of-conduct/`)
=> fix(CONTRIBUTING): broken coc link - I168

README.md
Signed-off-by: Archit garg4.ag@gmail.com
I found some Improper word choice as well as Improper formatting for that I have made changes and corrected that so, now It will be easier for everyone to read.
Please Merge this
=> fix(README): grammar

src/TemplateLibrary/TemplateCard.js
- style(TemplateCard): make background of card default to white
- remove irrelevant height and margin of inline element
=> style(TemplateCard): make background of card default to white

demo/src/index.js, package-lock.json, package.json, src/ContractEditor/index.js, src/plugins/ClausePlugin.js, src/plugins/README.md
Remove the dependency to `cicero`, use only in the `demo`
- Swap `cicero` from dependency to devDependency
- Update plugin `README` to indicate necessity of parsing and loading to be provided by users
- Apply code as example in `demo`
- Unsure if devDependency is the correct place for `cicero`, would like feedback
- N/A
=> refactor(*): remove cicero dependency to apply in demo

src/plugins/ClausePlugin.js
- When pasting a clause, an error would occur from slate where a node's key did not match its path
- fix(ClausePlugin): use withMutations to fix issue when pasting a clause node
- This issue had to do with ImmutableJS and how we were manipulating the node. This PR uses `withMutations` to set new data on a node. (https://immutable-js.github.io/immutable-js/)
- Pull Request #227
=> fix(ClausePlugin): use withMutations to fix issue when pasting a clause node

src/ErrorLogger/index.js
Signed-off-by: Dan Selman <danscode@selman.org>
- Protect ErrorComponent against non array input.
- cicero-core has also been updated to ensure errors from `parse` are `ParseException`
=> (fix) protect error component against bad input

src/TemplateLibrary/index.js
Allow user to search by `displayName`
- Include `displayName` in search functionality
- N/A
- N/A
=> fix(TemplateLibrary): include displayname in search - I240

src/ContractEditor/index.js, src/TemplateLibrary/index.js
- feat(ContractEditor): pass onUndoOrRedo prop through to editor
- fix(TemplateLibrary): fix library bug when a template does not have a display name
- Pull Request https://github.com/accordproject/markdown-editor/pull/206
=> feat(ContractEditor): pass onUndoOrRedo prop through to editor

package-lock.json, package.json, src/plugins/VariablePlugin.js, src/utilities/isToolbarMethod.js
Prevent application of markdown formatting to the content of variables in `lockText` mode
- List formatting options in object for lookup to determine if allowed
- Upgrade to latest version of `markdown-transform`
- Hyperlink action is listed as `undefined`
- N/A
=> fix(plugins): check variable for toolbar methods - I253

package-lock.json, package.json, src/ContractEditor/README.md, src/ContractEditor/index.js
- Pass the `readOnly` prop to disable the toolbar and edits
- N/A
- N/A
=> feat(ContractEditor): allow readOnly props

src/components/ClauseComponent.js, src/plugins/ClausePlugin.js
- Clause component icons for edit, test, and delete should not be shown in "read-only" mode
- fix(ClauseComponent): remove icons in read-only mode
=> fix(ClauseComponent): remove icons in read-only mode

demo/src/index.js, package-lock.json, package.json, src/ContractEditor/index.test.js
- chore(deps): update markdown-editor, markdown-slate, and cicero deps
=> chore(deps): update markdown-editor, markdown-slate, and cicero deps

src/ErrorLogger/Error.js
Related to https://github.com/accordproject/cicero-ui/issues/226
- feat(ErrorLogger): make Error Logger more resilient to missing error properties
=> feat(ErrorLogger): make Error Logger more resilient to missing error properties

src/components/styles.js, src/styles.css
I have checked and modified all the elements which weren't complying with the WCAG 2.0 Standards i.e. the contrast ratio was lesser than 4.5:1
- The following graphic should explain the changes made in a descriptive manner
- Builds upon the Pull Request #202
=> style(src): improve clause components a11y - I57

package-lock.json, package.json, src/ContractEditor/__snapshots__/index.test.js.snap
- Upgrade to Markdown Editor v0.9.8, https://github.com/accordproject/markdown-editor/releases/tag/v0.9.8
=> chore(deps): Upgrade markdown-editor dependency to 0.9.8

src/components/styles.js
Signed-off-by: Shrey Sachdeva <shreysachdeva.2000@gmail.com>
Change clause template background color from #ECF0FA to #F9FBFF to increase contrast. Increased contrast will improve accessibility and allow more flexibility for how we design future improvements.
- Change clause template background color from #ECF0FA to #F9FBFF
Earlier:
Now:
- N/A
- Issue #314
=> style(ClauseTemplate): change ClauseTemplate background color - I322

src/components/ClauseComponent.js, src/components/__snapshots__/index.test.js.snap, src/components/styles.js
Signed-off-by: elit-altum <manan.sharma311@gmail.com>
Continues: https://github.com/accordproject/markdown-editor/issues/124
- Modified the ClauseBackground UI according to the proposed changes.
- Added tooltips on all the ClauseHeader icons for more information.
- Design modifications and suggestions are welcome!
- Pull Request: #247
=> feat(ClauseHeader): added tooltips to icons

src/components/styles.js
Signed-off-by: elit-altum <manan.sharma311@gmail.com>
Fixed tooltips text getting selected by multiple clicks on the icons.
- Added the ```contentEditable="false"``` attribute to the tooltips ```styled.div```
Thanks @DianaLease for the suggestion! 💯 
- Issue #330
=> fix(styles.js): disables tooltip text selection - I330

.storybook/main.js, .storybook/manager.js, .storybook/preview.js, .storybook/theme.js, package-lock.json, package.json, src/stories/ContractEditor/ContractEditor.stories.js, src/stories/ContractEditor/docs.md, src/stories/ErrorLogger/ErrorLogger.stories.js, src/stories/ErrorLogger/docs.md
- Adds `@storybook/react` as a dependency.
- Access Storybook at port 9001 by running `npm run storybook`.
- Component stories can be added in `src/stories` folder with extension `.stories.js`
- N.A
- Issue #315
=> feat(*): add storybook for developer focused demo - I315

src/TemplateLibrary/index.js
Signed-off-by: nik72619c <nikhilsharmarockstar21@gmail.com>
This PR fixes the issue of extra clickable area  for the import buttons. The buttons would not have an extended area, but would rather be clickable till their content width.
Added the property `align-items: flex-end` so that their widths are not overflown
@DianaLease @irmerk Please review and suggest changes if any :)
=> feat(HeaderImport): fixed extra clickable area of import links

package-lock.json, package.json
This upgrades dependencies for:
- latest markdown transform `0.10.4`
- upcoming Cicero `0.20.19`
- corresponding version of the markdown editor for upcoming Cicero `0.20.10`
=> chore(dep) Upgrade dependencies for Cicero 0.20.10

demo/src/index.js, src/stories/ContractEditor/ContractEditor.stories.js, src/stories/Demo/Demo.stories.js
Signed-off-by: Arteev Raina <arteevraina@gmail.com>
`CSS` for the `BlockQuotes` has been added. Now, on using `Blockquotes` does not changes `Line-height`. 
-  Previous Pull Request #383 
Please Review and suggest changes @DianaLease @irmerk @Michael-Grover :)
=> feat(index.js): added css for blockquotes

demo/src/index.js, package-lock.json, package.json, src/ContractEditor/test/__snapshots__/index.test.js.snap
Support Slate's rule for normalizing children with empty text nodes.
- Update to newest `markdown-transform`
- N/A
- Closes #393
- [Transform PR #222](https://github.com/accordproject/markdown-transform/pull/222)
- [Slate #3637](https://github.com/ianstormtaylor/slate/pull/3637)
=> chore(package): increment markdown packages - I378

src/components/Conditional/index.js
Swap conditional nodes without normalizing the editor (which merges two similar text nodes between `removeNodes` and `insertNodes` function calls)
- Prevent merging of text nodes while removing and inserting
- N/A
=> fix(Conditional): swap without normalizing - I392

src/ContractEditor/plugins/withVariables.js
Prevent forward deletion at the end of a variable
- Check if cursor is at the end of a variable and is attempting to delete forward
- Unsure if this addresses @jeromesimeon's [comments](https://github.com/accordproject/cicero-ui/issues/374#issuecomment-621316324)
- `markdown-editor` PR [#340](https://github.com/accordproject/markdown-editor/pull/340)
=> fix(plugins): disable forward delete at end of variable - I374

demo/src/index.js, src/ContractEditor/index.js, src/ContractEditor/plugins/withClauses.js
- Remove unused refs
- Don't create debounced `onClauseUpdated` unless it's passed in. Don't require it since it's not needed if using the editor in `readOnly` mode
=> refactor(*): remove refs and only create debounced fn if fn exists

package-lock.json, package.json, src/ContractEditor/plugins/withClauses.js, src/ContractEditor/test/__snapshots__/index.test.js.snap
refactor(withClauses): remove unused editor parameter (left over from previous slate version where it was always automatically passed as the first argument from slate)
chore(dep): update md-editor dep
=> refactor(withClauses): remove unused editor parameter and update md-editor dep

src/ContractEditor/index.js
- feat(ContractEditor): pass clause props to Clause component
- refactor(ContractEditor): add linting disable comment & remove unused props
=> feat(ContractEditor): pass clause props to Clause component

package-lock.json, package.json, src/ContractEditor/index.js, src/ContractEditor/plugins/withClauses.js
- Prevents deleting last paragraph if it follows a clause template
- Prevents copying if selection begins or ends in a clause template
- Allows deleting all paragraphs between clause templates
- [`markdown-editor` #396](https://github.com/accordproject/markdown-editor/pull/396)
=> feat(ContractEditor): prevent copy partial clause et al

src/ContractEditor/plugins/withClauses.js, src/components/Clause/index.js
Add more `contentEditable` properties and `userSelect` CSS to non-editable properties according to this Slate slack convo: https://slate-js.slack.com/archives/C1RH7AXSS/p1588530291453700
This prevents a crash that can happen when Slate tries to find leaf nodes for these.
=> fix(*): fix properties and refactor input param
